### ISSUE TITLE
tf errors on using octomap with realsense camera

### ISSUE THREAD

**Issue by arpit15** [ros-planning/moveit_robots#61]
I am using Moveit in Indigo and ubuntu 14.04. I am getting following errors
`[ERROR] [1492050356.981666496]: Transform error: Lookup would require extrapolation into the future.  Requested time 1492050356.311039301 but the latest data is at time 1492050308.434982148, when looking up transform from frame [head] to frame [camera_rgb_optical_frame]
[ERROR] [1492050356.981708685]: Transform cache was not updated. Self-filtering may fail.`
I manually checked for the commits mentioned on this thread. All the changes are there in the moveit version I am using. 
I am trying to use realsense_camera with the baxter_gripper.launch file. My yaml file is [here](https://gist.github.com/arpit15/addd50baee142265abca3fa42f89e4d8) and my baxter_moveit_sensor_manager.xml is [here](https://gist.github.com/arpit15/9c06e444df78989f4a3d616249db0370)

**Comment by v4hn** [comment]
On Wed, Apr 12, 2017 at 07:30:04PM -0700, Arpit Agarwal wrote:
> `Requested time 1492050356.311039301 but the latest data is at time 1492050308.434982148`

You are missing about 48 seconds there. This looks like unsynchronized clocks to me.
Is the time difference roughly constant or does it increase over time?

**Comment by arpit15** [comment]
@v4hn I noted that the gap was constant and manually changed to align. Thanks. 
However after running the pipeline, I don't see a good octomap. The [output](https://gist.github.com/arpit15/c8053389b29f176af478597fe68e51e1) on the terminal seems fine.
Image with the moveit pipeline with octomap on
![image](https://cloud.githubusercontent.com/assets/4703676/25024434/efd3ce9e-206b-11e7-8f23-93283df93c73.png)
Moveit pipeline and point cloud shown
![image](https://cloud.githubusercontent.com/assets/4703676/25024454/0428115c-206c-11e7-9d87-0dcf98e7e199.png)

Kindly let me know in case I need to make any other parameter changes for the new sensor.

Thank you
Arpit

**Comment by arpit15** [comment]
I tried to use the depth image topic instead of using the point cloud. This seems to do a pretty good job for the octomap. Is there a possibility of updating the octomap manually like through the code? I want to plan the through the toy sometimes and other times without it. 
This is what I obtain by switching to depth image.
![image](https://cloud.githubusercontent.com/assets/4703676/25024822/945d502e-206d-11e7-9618-ea28d80f6632.png)
