### ISSUE TITLE
How Moveit Calculates Jacobian ?

### ISSUE THREAD

**Issue by deepakraina99** [ros-planning/moveit_robots#67]
I have calculated Geometric Jacobian for UR5 using DH parameters. But Jacobian given by MoveIt has different values for the same robot state. Do MoveIt use different way of calculating Jacobian ?

**Comment by rhaschke** [comment]
Such a question should be posed on ros.answers.org. If doing so, please provide more details, like how you compute the Jacobian. MoveIt's method is documented in the code:
https://github.com/ros-planning/moveit/blob/master/moveit_core/robot_state/src/robot_state.cpp#L1182
