### ISSUE TITLE
Move It! polar robot configuration not moving second joint

### ISSUE THREAD

**Issue by grafoteka** [ros-planning/moveit_robots#70]
Hi all! I'm fighting to create a polar robot configuration with Move It. 

The polar robot has 3 joints: rotational, rotational and prismatic.

![Polar robot](http://www.robotpark.com/academy/PG/Spherical-Robots-Robotpark.png)

I have model it in a xacro file and can move it with problems in Rviz with fake controllers.

[Rviz simulation YouTube](https://youtu.be/aMUPI4bxpEo)

Here is the xacro file of the robot (be care to uncomment the lines for the joint with the world) [link](https://github.com/grafoteka/Fotokite_arm/blob/master/arm_description/urdf/RRP.xacro)

And for launch it, this is the command:

    roslaunch arm_description rviz.launch

Then I follow the MoveIt! tutorial for a custom robot ([link](https://ros-planning.github.io/moveit_tutorials/doc/setup_assistant/setup_assistant_tutorial.html)) and generate all the files correctly, but as you can see in the next video, it only moves the first joint (rotational) and the third joint (prismatic), but not the second one (rotational). [Video](https://youtu.be/QGH57xaJD80)

This is the [workspace](https://github.com/grafoteka/Fotokite_arm) for all the project.

And for launch it, this is the command:

    roslaunch rrp_moveit demo.launch

I would apreciate some help in trying to fix this problem. 

Kinds regards, 
Jorge

**Comment by jrgnicho** [comment]
@grafoteka this question has already been posted in [ros answers](https://answers.ros.org/question/304617/move-it-polar-robot-configuration-not-moving-second-joint/) so I'll close this to avoid duplication.
