### ISSUE TITLE
Catkin_make error when using Moveit! on Baxter and Ubuntu 16.04 (ROS Kinetic)

### ISSUE THREAD

**Issue by ZhangHanbo** [ros-planning/moveit_robots#74]
Dear all
I met a catkin_make error when I use Moveit! on Baxter and Ubuntu 16.04 (ROS Kinetic). Detailed information is provided as follow:

> [ 91%] Built target control_toolbox_generate_messages_eus
> [ 91%] Built target control_toolbox_gencfg
> [ 91%] Built target control_toolbox_generate_messages_py
> [ 93%] Built target baxter_sim_controllers
> [ 93%] Built target gazebo_msgs_generate_messages_py
> [ 93%] Built target actionlib_generate_messages_py
> [ 93%] Built target actionlib_generate_messages_cpp
> [ 93%] Built target actionlib_generate_messages_eus
> [ 93%] Built target actionlib_generate_messages_lisp
> [ 93%] Built target actionlib_generate_messages_nodejs
> [ 93%] Built target controller_manager_msgs_generate_messages_py
> [ 93%] Built target controller_manager_msgs_generate_messages_eus
> [ 93%] Built target tf_generate_messages_nodejs
> [ 93%] Built target tf_generate_messages_cpp
> [ 93%] Built target std_srvs_generate_messages_nodejs
> [ 93%] Built target gazebo_ros_gencfg
> [ 93%] Built target controller_manager_msgs_generate_messages_nodejs
> [ 93%] Built target tf_generate_messages_eus
> [ 93%] Built target std_srvs_generate_messages_cpp
> [ 93%] Built target std_srvs_generate_messages_py
> [ 93%] Built target gazebo_msgs_generate_messages_nodejs
> [ 93%] Built target std_srvs_generate_messages_eus
> [ 93%] Built target std_srvs_generate_messages_lisp
> [ 93%] Built target tf_generate_messages_py
> [ 93%] Built target tf2_msgs_generate_messages_cpp
> [ 93%] Built target gazebo_msgs_generate_messages_cpp
> [ 93%] Built target tf2_msgs_generate_messages_lisp
> [ 93%] Built target tf_generate_messages_lisp
> [ 93%] Built target tf2_msgs_generate_messages_nodejs
> [ 93%] Built target controller_manager_msgs_generate_messages_cpp
> [ 93%] Built target tf2_msgs_generate_messages_eus
> [ 93%] Built target tf2_msgs_generate_messages_py
> [ 93%] Built target gazebo_msgs_generate_messages_lisp
> [ 93%] Built target controller_manager_msgs_generate_messages_lisp
> [ 93%] Built target gazebo_msgs_generate_messages_eus
> [ 94%] Built target baxter_gazebo_ros_control
> [ 95%] Built target baxter_sim_kinematics
> [ 96%] Built target kinematics
> [ 97%] Built target baxter_emulator
> [ 98%] Building CXX object moveit_robots/baxter/baxter_ikfast_left_arm_plugin/CMakeFiles/baxter_left_arm_moveit_ikfast_plugin.dir/src/baxter_left_arm_ikfast_moveit_plugin.cpp.o
> c++: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
> moveit_robots/baxter/baxter_ikfast_left_arm_plugin/CMakeFiles/baxter_left_arm_moveit_ikfast_plugin.dir/build.make:62: recipe for target 'moveit_robots/baxter/baxter_ikfast_left_arm_plugin/CMakeFiles/baxter_left_arm_moveit_ikfast_plugin.dir/src/baxter_left_arm_ikfast_moveit_plugin.cpp.o' failed
> make[2]: *** [moveit_robots/baxter/baxter_ikfast_left_arm_plugin/CMakeFiles/baxter_left_arm_moveit_ikfast_plugin.dir/src/baxter_left_arm_ikfast_moveit_plugin.cpp.o] Error 4
> CMakeFiles/Makefile2:6799: recipe for target 'moveit_robots/baxter/baxter_ikfast_left_arm_plugin/CMakeFiles/baxter_left_arm_moveit_ikfast_plugin.dir/all' failed
> make[1]: *** [moveit_robots/baxter/baxter_ikfast_left_arm_plugin/CMakeFiles/baxter_left_arm_moveit_ikfast_plugin.dir/all] Error 2
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2
> Invoking "make -j1 -l1" failed

Does Moveit! support Baxter on Kinetic? Or is anything wrong with my ROS?
I followed the procedure of the Moveit! Tutorial on this link to install Moveit!:
http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/getting_started/getting_started.html
and followed the procedure on this link to install Baxter's Moveit!:
http://sdk.rethinkrobotics.com/wiki/MoveIt_Tutorial

**Comment by rhaschke** [comment]
This is an internal gcc error and should be reported to gcc folks:
> c++: internal compiler error: Killed (program cc1plus)

I have seen such errors with the ikfast plugins in the past as well, but don't remember the particular solution. Maybe, try to regenerate the ikfast plugins?

**Comment by ZhangHanbo** [comment]
> This is an internal gcc error and should be reported to gcc folks:
> 
> > c++: internal compiler error: Killed (program cc1plus)
> 
> I have seen such errors with the ikfast plugins in the past as well, but don't remember the particular solution. Maybe, try to regenerate the ikfast plugins?

I tried to build Moveit! from source. However, another issue occurred:

> Errors     << moveit_core:make /home/zhb/ros_ws/logs/moveit_core/build.make.002.log
> In file included from /home/zhb/ros_ws/src/moveit/moveit_core/utils/src/robot_model_test_utils.cpp:42:0:
> /home/zhb/ros_ws/src/moveit/moveit_core/utils/include/moveit/utils/robot_model_test_utils.h:48:37: fatal error: moveit_resources/config.h: No such file or directory
> compilation terminated.
> make[2]: *** [utils/CMakeFiles/moveit_test_utils.dir/src/robot_model_test_utils.cpp.o] Error 1
> make[1]: *** [utils/CMakeFiles/moveit_test_utils.dir/all] Error 2
> make: *** [all] Error 2

Any idea to solve this problem?

**Comment by rhaschke** [comment]
Install the missing dependency: ros-melodic-moveit-resources

**Comment by ZhangHanbo** [comment]
> Install the missing dependency: ros-melodic-moveit-resources

Thanks for helping me to solve this problem. By following these steps, I successfully installed all the packages I want. I attach them here and hope to help others who want to install them:

https://zhuanlan.zhihu.com/p/60178371

**Comment by rhaschke** [comment]
I just pushed a fix to the github master branch to fix the last issue.
Thanks for sharing your install instructions. I couldn't recognize a strong deviation from the MoveIt install instructions though. Could you please shortly summarize the bugs you encountered and steps you took to mitigate them? The only open issue, I could spot so far is:
- Build `baxter_gazebo` with C++11. Please file an issue (or better PR with a fix) against this repo.

**Comment by ZhangHanbo** [comment]
> I just pushed a fix to the github master branch to fix the last issue.
> Thanks for sharing your install instructions. I couldn't recognize a strong deviation from the MoveIt install instructions though. Could you please shortly summarize the bugs you encountered and steps you took to mitigate them? The only open issue, I could spot so far is:
> 
> * Build `baxter_gazebo` with C++11. Please file an issue (or better PR with a fix) against this repo.

No more issues are encountered by me, except for these:
1) **gcc internal error at the beginning**. I don't know why it occurs and when it will occur. I solve it by building Moveit! from source. I guess that it may correspond to the dependencies?
2) **Hang on forever when catkin build**. I guess it may be because the workspace is first built by catkin_make. It happens when the moveit_core pkg is being processed. And it CAN NOT be solved by just deleting all generated files (e.g. bin/, devel/, build/ and log/).
3) **Lack of moveit_sources/config.h file**.
4) **error of baxter_gazebo pkg**. Like you mentioned.

**Comment by ZhangHanbo** [comment]
For the second issue, **hang on forever when catkin build**, I use a whole day to try to solve it. Finally, I solve it by reinstalling Ubuntu 16.04........
I am not so familiar with these strange problems, and reinstalling the OS is the best way for me. Hahaha

**Comment by rhaschke** [comment]
> 1. gcc internal error at the beginning.

I think, I have seen this when running out-of-memory, for example compiling on several parallel processors.

> 2. Hang on forever when catkin build.

catkin_make and catkin both create some hidden files or folders in ros_ws. But they shouldn't interfere.
You probably didn't kept the console output?

> 3. Lack of moveit_sources/config.h file.

Should be fixed.

> 4. Error of baxter_gazebo pkg

Please file a separate issue / PR there.

**Comment by ZhangHanbo** [comment]
Thanks for your patience
