### ISSUE TITLE
How to use chomp planner for baxter

### ISSUE THREAD

**Issue by Hubert51** [ros-planning/moveit_robots#75]
I am trying to use chomp planner for baxter. I change the following line in move_group.py
`  <arg name="planner" default="ompl" />` to `  <arg name="planner" default="chomp" />`

It gives me error 
`[ERROR] [1561156848.404331657]: Exception while loading planner 'chomp_interface/CHOMPPlanner': According to the loaded plugin descriptions the class chomp_interface/CHOMPPlanner with base class type planning_interface::PlannerManager does not exist. Declared types are  ompl_interface/OMPLPlanner
Available plugins: ompl_interface/OMPLPlanner`

Do I need to change some other part of code?

**Comment by rhaschke** [comment]
Looks like you didn't installed the `ros-melodic-moveit-planners-chomp` package yet.
Using the latest source of `moveit_robots` you can benefit from https://github.com/ros-planning/moveit_robots/pull/73, which allows to use the chomp planner like this:
`roslaunch baxter_moveit_config demo_dummy.launch planner:=chomp`

**Comment by Hubert51** [comment]
Since now I am using ros indigo. Can I install chomp under this version?

**Comment by knorth55** [comment]
I build `moveit` `master` branch from source and I can run `CHOMP` planner with Baxter in the real world!
I use Ubuntu 16.04 + Kinetic.

**Comment by rhaschke** [comment]
Sorry, probably chomp isn't working on Indigo, which is EOL.

**Comment by Hubert51** [comment]
Thank you! I will try some more to make sure
