### ISSUE TITLE
Why IKFAST solver doesn't work and appear error like ABORTED: No motion plan found. No execution attempted.

### ISSUE THREAD

**Issue by hetolin** [ros-planning/moveit_robots#80]
hi, I generated the IKFAST for Baxter by following the official website step by step(https://sdk.rethinkrobotics.com/wiki/Custom_IKFast_for_your_Baxter). 

But it seems that the generated  IKFAST solver doesn't work anymore (it always outputs:`ABORTED: No motion plan found. No execution attempted.`)while the default KDL solver can generate motion normally. What is the problem with it? ABORTED: No motion plan found. No execution attempted. Is it that IKFAST is far less effective than KDL?

**Comment by rhaschke** [comment]
I suggest trying the official MoveIt tutorial as well:
https://ros-planning.github.io/moveit_tutorials/doc/ikfast/ikfast_tutorial.html

Instead of trying to plan, can you move the arm(s) in rviz? The latter only involves the IK solver, but not the planner.

**Comment by hetolin** [comment]
Thanks for your prompt reply. 
Yes, I can move the arms in Rviz. But when I use the `self.group.set_pose_target(pose_goal)` and `self.group.go()` to plan, it doesn't work. So what is the matter with it?

**Comment by rhaschke** [comment]
Please check the output from the move_group node in more detail. The given message doesn't hint at IKFast or anything else specific. Probably there are more informative messages before. Maybe collisions at your target or start pose...

**Comment by hetolin** [comment]
Hi, The following are the outputs of the move_group node. And when I change to default KDL solver, it can work well.  So It means that there is no problem with my start pose or target pose. It's a pity that I didn't found such a solution about IKFAST not working problem on Baxter. All the answers are that IKFAST is a perfect tool compared with KDL or TRAC-IK. Or maybe IKFAST is not suitable for Baxter? It just really knocked me down.

===================================================
You can start planning now!

[ INFO] [1590715982.270201257, 135.857000000]: Loading robot model 'baxter'...
[ WARN] [1590715982.270232649, 135.857000000]: Skipping virtual joint 'world_joint' because its child frame 'base' does not match the URDF frame 'world'
[ INFO] [1590715982.270242709, 135.857000000]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ INFO] [1590715982.349001273, 135.933000000]: left_s0 -1.70168 1.70168 1
[ INFO] [1590715982.349030061, 135.933000000]: left_s1 -2.147 1.047 1
[ INFO] [1590715982.349037996, 135.933000000]: left_e0 -3.05418 3.05418 1
[ INFO] [1590715982.349046672, 135.933000000]: left_e1 -0.05 2.618 1
[ INFO] [1590715982.349053541, 135.933000000]: left_w0 -3.059 3.059 1
[ INFO] [1590715982.349061803, 135.933000000]: left_w1 -1.5708 2.094 1
[ INFO] [1590715982.349069228, 135.933000000]: left_w2 -3.059 3.059 1
[ INFO] [1590715982.368830070, 135.951000000]: right_s0 -1.70168 1.70168 1
[ INFO] [1590715982.368853763, 135.951000000]: right_s1 -2.147 1.047 1
[ INFO] [1590715982.368861405, 135.951000000]: right_e0 -3.05418 3.05418 1
[ INFO] [1590715982.368868108, 135.951000000]: right_e1 -0.05 2.618 1
[ INFO] [1590715982.368874212, 135.951000000]: right_w0 -3.059 3.059 1
[ INFO] [1590715982.368881010, 135.951000000]: right_w1 -1.5708 2.094 1
[ INFO] [1590715982.368889083, 135.951000000]: right_w2 -3.059 3.059 1
[ INFO] [1590715982.413758897, 135.995000000]: Starting scene monitor
[ INFO] [1590715982.415982960, 135.997000000]: Listening to '/move_group/monitored_planning_scene'
[ INFO] [1590715983.239727685, 136.821000000]: Constructing new MoveGroup connection for group 'both_arms' in namespace ''
[ INFO] [1590715984.271612907, 137.852000000]: Ready to take commands for planning group both_arms.
[ INFO] [1590715984.271660322, 137.852000000]: Looking around: no
[ INFO] [1590715984.271676050, 137.852000000]: Replanning: no
[ WARN] [1590715984.285051654, 137.866000000]: Interactive marker 'EE:goal_right_gripper' contains unnormalized quaternions. This warning will only be output once but may be true for others; enable DEBUG messages for ros.rviz.quaternions to see more details.
[ WARN] [1590716018.454614488, 171.064000000]: MessageFilter [target=/world ]: Discarding message from [/grasp_ycb_mug_realworld_19089_1590716014395] due to empty frame_id.  This message will only print once.
[ INFO] [1590716021.778655925, 174.223000000]: Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.
[ INFO] [1590716021.778801346, 174.223000000]: Planning attempt 1 of at most 1
[ INFO] [1590716021.778890583, 174.223000000]: Starting state is just outside bounds (joint 'left_s1'). Assuming within bounds.
[ INFO] [1590716021.780028455, 174.225000000]: Planner configuration 'left_arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1590716021.780421820, 174.225000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1590716021.791379380, 174.234000000]: RRTConnect: Created 5 states (2 start + 3 goal)
[ INFO] [1590716021.791440652, 174.234000000]: Solution found in 0.011171 seconds
[ INFO] [1590716021.802078376, 174.245000000]: SimpleSetup: Path simplification took 0.010421 seconds and changed from 4 to 2 states
[ INFO] [1590716021.802875751, 174.246000000]: Planning adapters have added states at index positions: [ 0 ]
[ERROR] [1590716025.554000, 177.803000]: /joint_trajectory_action_server_py_hetolin_17605_2194351549986795923: Exceeded Max Goal Velocity Threshold for left arm
[ WARN] [1590716025.554617749, 177.804000000]: Controller /robot/limb/left failed with error code GOAL_TOLERANCE_VIOLATED
[ WARN] [1590716025.554678962, 177.804000000]: Controller handle /robot/limb/left reports status ABORTED
[ INFO] [1590716025.554700829, 177.804000000]: Completed trajectory execution with status ABORTED ...
[ INFO] [1590716025.604880279, 177.849000000]: Received event 'stop'
[ INFO] [1590716025.678634760, 177.918000000]: Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.
[ INFO] [1590716025.678874092, 177.918000000]: Planning attempt 1 of at most 1
[ INFO] [1590716025.679437997, 177.919000000]: Planner configuration 'left_arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1590716025.679707039, 177.919000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1590716025.679756787, 177.919000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1590716025.679779597, 177.919000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1590716025.679802179, 177.919000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ERROR] [1590716030.680914030, 182.592000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716030.680951825, 182.592000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ERROR] [1590716030.680991276, 182.593000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716030.681013804, 182.593000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ERROR] [1590716030.682136363, 182.594000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716030.682159263, 182.594000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ERROR] [1590716030.684503761, 182.596000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716030.684530930, 182.596000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ WARN] [1590716030.684603144, 182.596000000]: ParallelPlan::solve(): Unable to find solution by any of the threads in 5.005021 seconds
[ INFO] [1590716030.685289615, 182.597000000]: Unable to solve the planning problem
[ INFO] [1590716030.685510351, 182.597000000]: Received event 'stop'
[ INFO] [1590716032.254647481, 183.998000000]: Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.
[ INFO] [1590716032.254717850, 183.998000000]: Planning attempt 1 of at most 1
[ INFO] [1590716032.255170406, 183.998000000]: Planner configuration 'left_arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1590716032.255406312, 183.998000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1590716032.255426977, 183.998000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1590716032.255447667, 183.998000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1590716032.255471013, 183.998000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ERROR] [1590716037.256642247, 188.646000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716037.256671581, 188.646000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ERROR] [1590716037.257849591, 188.647000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716037.257875422, 188.647000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ERROR] [1590716037.260246509, 188.650000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716037.260267528, 188.650000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ERROR] [1590716037.260830998, 188.650000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716037.260849280, 188.650000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ WARN] [1590716037.260880422, 188.650000000]: ParallelPlan::solve(): Unable to find solution by any of the threads in 5.005577 seconds
[ INFO] [1590716037.354234140, 188.739000000]: Unable to solve the planning problem
[ INFO] [1590716037.354534022, 188.739000000]: Received event 'stop'
[ INFO] [1590716037.563610449, 188.945000000]: Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.
[ INFO] [1590716037.563715597, 188.945000000]: Planning attempt 1 of at most 1
[ INFO] [1590716037.564162215, 188.946000000]: Planner configuration 'left_arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1590716037.564395876, 188.946000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1590716037.564427724, 188.946000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1590716037.564449823, 188.946000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1590716037.564471696, 188.946000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ERROR] [1590716042.564978345, 193.584000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716042.565034947, 193.584000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ERROR] [1590716042.572872107, 193.595000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716042.572899624, 193.595000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ERROR] [1590716042.573073076, 193.595000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716042.573089486, 193.595000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ERROR] [1590716042.573144936, 193.595000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716042.573164945, 193.595000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ WARN] [1590716042.573190594, 193.595000000]: ParallelPlan::solve(): Unable to find solution by any of the threads in 5.008915 seconds
[ INFO] [1590716042.632065763, 193.649000000]: Unable to solve the planning problem
[ INFO] [1590716042.632774248, 193.649000000]: Received event 'stop'
[ INFO] [1590716042.895175849, 193.895000000]: Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.
[ INFO] [1590716042.895311876, 193.895000000]: Planning attempt 1 of at most 1
[ INFO] [1590716042.895927911, 193.895000000]: Planner configuration 'left_arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1590716042.896218896, 193.895000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1590716042.896268892, 193.895000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1590716042.896314961, 193.895000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1590716042.896439600, 193.895000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ERROR] [1590716047.897371845, 198.394000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716047.897459498, 198.394000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ERROR] [1590716047.902298991, 198.399000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716047.902331986, 198.399000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ERROR] [1590716047.905393074, 198.402000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716047.905422244, 198.402000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ERROR] [1590716047.905715412, 198.403000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716047.905735911, 198.403000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ WARN] [1590716047.905768277, 198.403000000]: ParallelPlan::solve(): Unable to find solution by any of the threads in 5.009687 seconds
[ INFO] [1590716047.931269796, 198.430000000]: Unable to solve the planning problem
[ INFO] [1590716047.931508823, 198.430000000]: Received event 'stop'
[ INFO] [1590716048.147184023, 198.626000000]: Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.
[ INFO] [1590716048.147371730, 198.626000000]: Planning attempt 1 of at most 1
[ INFO] [1590716048.148068451, 198.626000000]: Planner configuration 'left_arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1590716048.148548928, 198.627000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1590716048.148628364, 198.627000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1590716048.148692958, 198.627000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1590716048.149299567, 198.627000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ERROR] [1590716053.148521524, 203.188000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716053.148618403, 203.188000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ERROR] [1590716053.149215196, 203.188000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716053.149234294, 203.188000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ERROR] [1590716053.150383898, 203.190000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716053.150406833, 203.190000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ERROR] [1590716053.151845863, 203.190000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716053.151878392, 203.191000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ WARN] [1590716053.151953175, 203.191000000]: ParallelPlan::solve(): Unable to find solution by any of the threads in 5.003651 seconds
[ INFO] [1590716053.235349692, 203.264000000]: Unable to solve the planning problem
[ INFO] [1590716053.235825890, 203.264000000]: Received event 'stop'
[ INFO] [1590716053.467403715, 203.477000000]: Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.
[ INFO] [1590716053.467547473, 203.477000000]: Planning attempt 1 of at most 1
[ INFO] [1590716053.468014865, 203.478000000]: Planner configuration 'left_arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1590716053.468286962, 203.479000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1590716053.468314377, 203.479000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1590716053.468356232, 203.479000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1590716053.468408324, 203.479000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ERROR] [1590716058.473248987, 208.132000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716058.473295637, 208.132000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ERROR] [1590716058.473912007, 208.133000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716058.473928827, 208.133000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ERROR] [1590716058.475876572, 208.135000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716058.475896289, 208.135000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ERROR] [1590716058.475972758, 208.135000000]: RRTConnect: Unable to sample any valid states for goal tree
[ INFO] [1590716058.475991529, 208.135000000]: RRTConnect: Created 1 states (1 start + 0 goal)
[ WARN] [1590716058.476021102, 208.135000000]: ParallelPlan::solve(): Unable to find solution by any of the threads in 5.007862 seconds
[ INFO] [1590716058.603050617, 208.246000000]: Unable to solve the planning problem
[ INFO] [1590716058.605134018, 208.246000000]: Received event 'stop'

**Comment by rhaschke** [comment]
I'm not sure, what you actually did, because there are two planning requests reported.
For the first one it states that planning succeeded:
```
[ INFO] [1590716021.780421820, 174.225000000]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1590716021.791379380, 174.234000000]: RRTConnect: Created 5 states (2 start + 3 goal)
[ INFO] [1590716021.791440652, 174.234000000]: Solution found in 0.011171 seconds
[ INFO] [1590716021.802078376, 174.245000000]: SimpleSetup: Path simplification took 0.010421 seconds and changed from 4 to 2 states
[ INFO] [1590716021.802875751, 174.246000000]: Planning adapters have added states at index positions: [ 0 ]
```
However, executing this plan, your controller (or the one from Baxter) complains:
```
[ERROR] [1590716025.554000, 177.803000]: /joint_trajectory_action_server_py_hetolin_17605_2194351549986795923: Exceeded Max Goal Velocity Threshold for left arm
[ WARN] [1590716025.554617749, 177.804000000]: Controller /robot/limb/left failed with error code GOAL_TOLERANCE_VIOLATED
[ WARN] [1590716025.554678962, 177.804000000]: Controller handle /robot/limb/left reports status ABORTED
[ INFO] [1590716025.554700829, 177.804000000]: Completed trajectory execution with status ABORTED ...
```

So, this is not related to IKFast. Please, read your logs more carefully yourself.
Closing here, because that's not an issue with MoveIt. Please post a question on https://answers.ros.org if you need more help. The issues here are for bug reports only.
